import datetime as dt

from sqlalchemy import ForeignKey, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db import Base
from app.models.types import GUID, new_uuid


class ClarificationQuestion(Base):
    """Generated by the policy engine when a claim is flagged for missing
    context. Answering it (see resolved_by_claim_id) creates a new claim with
    source_type=clinician_judgment, rather than the model silently guessing."""

    __tablename__ = "clarification_questions"

    id: Mapped[GUID] = mapped_column(GUID(), primary_key=True, default=new_uuid)
    encounter_id: Mapped[GUID] = mapped_column(GUID(), ForeignKey("encounters.id"))
    triggering_claim_id: Mapped[GUID] = mapped_column(GUID(), ForeignKey("claims.id"))
    question_text: Mapped[str] = mapped_column(Text)
    # Grounding citation (Phase 4) that justified why this info is required,
    # e.g. a guideline snippet's documentation requirements for this claim type.
    grounding_citation_id: Mapped[GUID | None] = mapped_column(
        GUID(), ForeignKey("grounding_citations.id"), nullable=True
    )
    resolved: Mapped[bool] = mapped_column(default=False)
    resolved_by_claim_id: Mapped[GUID | None] = mapped_column(
        GUID(), ForeignKey("claims.id"), nullable=True
    )
    created_at: Mapped[dt.datetime] = mapped_column(default=dt.datetime.utcnow)
    resolved_at: Mapped[dt.datetime | None] = mapped_column(nullable=True)
