"""add policy verdicts table and grounding citation verdict fk

Revision ID: 3e51b38dbac2
Revises: 50f800c84a8c
Create Date: 2026-07-23 23:48:37.337492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.types

# revision identifiers, used by Alembic.
revision: str = '3e51b38dbac2'
down_revision: Union[str, None] = '50f800c84a8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: the checkpoint_* tables that autogenerate detected as "removed"
    # are intentionally excluded here -- they're owned and created by
    # LangGraph's PostgresSaver.setup() (see app/pipeline/checkpointer.py),
    # not by these SQLAlchemy models, and must never be dropped by Alembic.
    op.create_table('policy_verdicts',
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('claim_id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('check_type', sa.Enum('support', 'contradiction', 'temporal_ambiguity', 'missing_context', 'clinical_safety', name='policychecktype', native_enum=False), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'grounding_citations', 'policy_verdicts', ['verdict_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'grounding_citations', type_='foreignkey')
    op.drop_table('policy_verdicts')
    # ### end Alembic commands ###
