"""add category to clinical knowledge chunks

Revision ID: 50f800c84a8c
Revises: c140da45174f
Create Date: 2026-07-23 23:39:31.511205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50f800c84a8c'
down_revision: Union[str, None] = 'c140da45174f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'clinical_knowledge_chunks',
        sa.Column('category', sa.String(), nullable=False, server_default='documentation_standard'),
    )
    op.alter_column('clinical_knowledge_chunks', 'category', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clinical_knowledge_chunks', 'category')
    # ### end Alembic commands ###
