"""add is_rejected to soap_note_lines

Revision ID: 5a9fec5f4472
Revises: 94979f4d3b0f
Create Date: 2026-07-24 00:46:58.287139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a9fec5f4472'
down_revision: Union[str, None] = '94979f4d3b0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'soap_note_lines',
        sa.Column('is_rejected', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('soap_note_lines', 'is_rejected')
    # ### end Alembic commands ###
