"""add mock_ehr_submissions table

Revision ID: 63014754fef5
Revises: 5a9fec5f4472
Create Date: 2026-07-24 01:10:31.476812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.models.types


# revision identifiers, used by Alembic.
revision: str = '63014754fef5'
down_revision: Union[str, None] = '5a9fec5f4472'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mock_ehr_submissions',
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('encounter_id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('note_id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('bundle', sa.JSON(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['note_id'], ['soap_notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mock_ehr_submissions')
    # ### end Alembic commands ###
