"""initial schema

Revision ID: 7c4cea4a14df
Revises: 
Create Date: 2026-07-23 16:00:14.012831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.types


# revision identifiers, used by Alembic.
revision: str = '7c4cea4a14df'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('encounters',
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('patient_id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('clinician_id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('in_progress', 'drafted', 'reviewed', 'signed', name='encounterstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['clinician_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claims',
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('encounter_id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('claim_type', sa.Enum('symptom', 'history', 'medication', 'allergy', 'vital', 'exam_finding', 'assessment', 'plan_item', 'other', name='claimtype', native_enum=False), nullable=False),
    sa.Column('source_type', sa.Enum('patient_speech', 'caregiver_report', 'clinician_observation', 'ehr_data', 'device_data', 'clinician_judgment', name='sourcetype', native_enum=False), nullable=False),
    sa.Column('source_reference', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('proposed', 'supported', 'contradicted', 'ambiguous', 'missing_context', 'unsupported', 'accepted', 'edited', 'rejected', name='claimstatus', native_enum=False), nullable=False),
    sa.Column('normalized_code_system', sa.String(), nullable=True),
    sa.Column('normalized_code', sa.String(), nullable=True),
    sa.Column('normalized_display', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('soap_notes',
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('encounter_id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'under_review', 'signed', name='notestatus', native_enum=False), nullable=False),
    sa.Column('signed_by', app.models.types.GUID(length=36), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['signed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transcript_segments',
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('encounter_id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('speaker_role', sa.Enum('patient', 'caregiver', 'clinician', 'system', name='speakerrole', native_enum=False), nullable=False),
    sa.Column('speaker_identifier', sa.String(), nullable=True),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claim_edges',
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('source_claim_id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('target_claim_id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('relation', sa.Enum('supports', 'contradicts', 'refines', 'duplicates', 'depends_on_temporal_context', name='edgerelation', native_enum=False), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['target_claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grounding_citations',
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('claim_id', app.models.types.GUID(length=36), nullable=True),
    sa.Column('verdict_id', app.models.types.GUID(length=36), nullable=True),
    sa.Column('source_type', sa.Enum('guideline', 'drug_data', 'prior_encounter', 'coded_vocabulary', name='groundingsourcetype', native_enum=False), nullable=False),
    sa.Column('source_identifier', sa.String(), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('soap_note_lines',
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('note_id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('section', sa.Enum('subjective', 'objective', 'assessment', 'plan', name='soapsection', native_enum=False), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_conflict', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['soap_notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attestations',
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('encounter_id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('note_version_id', app.models.types.GUID(length=36), nullable=True),
    sa.Column('note_line_id', app.models.types.GUID(length=36), nullable=True),
    sa.Column('claim_id', app.models.types.GUID(length=36), nullable=True),
    sa.Column('actor_id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('action', sa.Enum('accepted', 'edited', 'rejected', 'added', name='attestationaction', native_enum=False), nullable=False),
    sa.Column('before_value', sa.Text(), nullable=True),
    sa.Column('after_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['note_line_id'], ['soap_note_lines.id'], ),
    sa.ForeignKeyConstraint(['note_version_id'], ['soap_notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clarification_questions',
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('encounter_id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('triggering_claim_id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('grounding_citation_id', app.models.types.GUID(length=36), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by_claim_id', app.models.types.GUID(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['grounding_citation_id'], ['grounding_citations.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['triggering_claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('soap_note_line_claims',
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('line_id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('claim_id', app.models.types.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['line_id'], ['soap_note_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('soap_note_line_claims')
    op.drop_table('clarification_questions')
    op.drop_table('attestations')
    op.drop_table('soap_note_lines')
    op.drop_table('grounding_citations')
    op.drop_table('claim_edges')
    op.drop_table('transcript_segments')
    op.drop_table('soap_notes')
    op.drop_table('claims')
    op.drop_table('encounters')
    op.drop_table('users')
    # ### end Alembic commands ###
