"""add vocabulary terms table

Revision ID: 94979f4d3b0f
Revises: 3e51b38dbac2
Create Date: 2026-07-24 00:20:30.107978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.types
import pgvector.sqlalchemy.vector


# revision identifiers, used by Alembic.
revision: str = '94979f4d3b0f'
down_revision: Union[str, None] = '3e51b38dbac2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vocabulary_terms',
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('code_system', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('display', sa.String(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vocabulary_terms')
    # ### end Alembic commands ###
