"""add clinical knowledge and patient history chunk tables

Revision ID: c140da45174f
Revises: 2652d2bf0322
Create Date: 2026-07-23 23:26:03.294358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.types
import pgvector.sqlalchemy.vector


# revision identifiers, used by Alembic.
revision: str = 'c140da45174f'
down_revision: Union[str, None] = '2652d2bf0322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_knowledge_chunks',
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('source_identifier', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_history_chunks',
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('patient_id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('source_encounter_label', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient_history_chunks')
    op.drop_table('clinical_knowledge_chunks')
    # ### end Alembic commands ###
